name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - uses: actions/checkout@v2

      # Fetch all branches and tags to ensure the history is complete and up-to-date.
      - name: Fetch all history for all tags and branches
        run: git fetch --unshallow || git fetch

      # Merge changes from the remote main branch to the local copy
      - name: Merge changes from the main branch
        run: git pull origin main

      # Generate the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: newnezz
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: false

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
